//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medicus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArretDeTravail {
            get {
                object obj = ResourceManager.GetObject("ArretDeTravail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AutreBilan {
            get {
                object obj = ResourceManager.GetObject("AutreBilan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BonExamenRadio {
            get {
                object obj = ResourceManager.GetObject("BonExamenRadio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CertificationMedical {
            get {
                object obj = ResourceManager.GetObject("CertificationMedical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ConsultationClinique {
            get {
                object obj = ResourceManager.GetObject("ConsultationClinique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DiagnosticDiab {
            get {
                object obj = ResourceManager.GetObject("DiagnosticDiab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream facebookme_lZ4iKc6J {
            get {
                return ResourceManager.GetStream("facebookme_lZ4iKc6J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff1\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1036\deflangfe1036\themelang1036\themelangfe0\themelangcs1025{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMC {
            get {
                return ResourceManager.GetString("IMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeDattente {
            get {
                object obj = ResourceManager.GetObject("ListeDattente", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeRendezVous {
            get {
                object obj = ResourceManager.GetObject("ListeRendezVous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicus.
        /// </summary>
        internal static string Logiciel {
            get {
                return ResourceManager.GetString("Logiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cette écriture est générer automatiquement! vous ne pouvez pas la supprimer dans ce module.
        /// </summary>
        internal static string MessageBoxEcriutreautomatique {
            get {
                return ResourceManager.GetString("MessageBoxEcriutreautomatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas le droit d&apos;accéder a ce module.
        /// </summary>
        internal static string MessageBoxPrivilége {
            get {
                return ResourceManager.GetString("MessageBoxPrivilége", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmez cette opération.
        /// </summary>
        internal static string MessageBoxQuestionOperation {
            get {
                return ResourceManager.GetString("MessageBoxQuestionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MouvementCaisse {
            get {
                object obj = ResourceManager.GetObject("MouvementCaisse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération a été annulée.
        /// </summary>
        internal static string Opérationéchouée {
            get {
                return ResourceManager.GetString("Opérationéchouée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération a été annulée , la transaction a échoué.
        /// </summary>
        internal static string OpérationéchouéeTransaction {
            get {
                return ResourceManager.GetString("OpérationéchouéeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération terminée avec succès.
        /// </summary>
        internal static string OperationSuccées {
            get {
                return ResourceManager.GetString("OperationSuccées", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ordonnance {
            get {
                object obj = ResourceManager.GetObject("Ordonnance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OrdonnanceA4 {
            get {
                object obj = ResourceManager.GetObject("OrdonnanceA4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RecuDePaiement {
            get {
                object obj = ResourceManager.GetObject("RecuDePaiement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportBonExamen {
            get {
                object obj = ResourceManager.GetObject("ReportBonExamen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportCaisse {
            get {
                object obj = ResourceManager.GetObject("ReportCaisse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportConstante {
            get {
                object obj = ResourceManager.GetObject("ReportConstante", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportCredti {
            get {
                object obj = ResourceManager.GetObject("ReportCredti", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeMotif {
            get {
                object obj = ResourceManager.GetObject("ReportListeMotif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeMotifDepense {
            get {
                object obj = ResourceManager.GetObject("ReportListeMotifDepense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeSpecialité {
            get {
                object obj = ResourceManager.GetObject("ReportListeSpecialité", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeTypeCas {
            get {
                object obj = ResourceManager.GetObject("ReportListeTypeCas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportMedecin {
            get {
                object obj = ResourceManager.GetObject("ReportMedecin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportMembership {
            get {
                object obj = ResourceManager.GetObject("ReportMembership", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneConstante {
            get {
                object obj = ResourceManager.GetObject("ReportOneConstante", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneMedecin {
            get {
                object obj = ResourceManager.GetObject("ReportOneMedecin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneMembership {
            get {
                object obj = ResourceManager.GetObject("ReportOneMembership", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOnePatient {
            get {
                object obj = ResourceManager.GetObject("ReportOnePatient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneVisite {
            get {
                object obj = ResourceManager.GetObject("ReportOneVisite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportPatients {
            get {
                object obj = ResourceManager.GetObject("ReportPatients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportRendezVous {
            get {
                object obj = ResourceManager.GetObject("ReportRendezVous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportTableauDeBord {
            get {
                object obj = ResourceManager.GetObject("ReportTableauDeBord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportVisiteDetailPatient {
            get {
                object obj = ResourceManager.GetObject("ReportVisiteDetailPatient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion Cabinet médical.
        /// </summary>
        internal static string SiteWeb {
            get {
                return ResourceManager.GetString("SiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soins_dentaires {
            get {
                object obj = ResourceManager.GetObject("soins_dentaires", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VisiteGeneral {
            get {
                object obj = ResourceManager.GetObject("VisiteGeneral", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
